# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "luajit-decompiler-v2"

[target.luajit-decompiler-v2]
type = "executable"
sources = [
    "main.h", 
    "main.cpp",
    "ast/**.h",
    "ast/**.cpp",
    "bytecode/**.h",
    "bytecode/**.cpp",
    "lua/**.h",
    "lua/**.cpp"
]
compile-features = ["cxx_std_20"]
link-libraries = ["shlwapi.lib"]
